linters-settings:
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  gocyclo:
    min-complexity: 15
  
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  
  # gomnd yerine mnd kullanılıyor (golangci-lint v1.52+)
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
  
  govet:
    enable:
      - shadow  # check-shadowing yerine shadow linter'ı aktif
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  
  lll:
    line-length: 140
  
  misspell:
    locale: US
  
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  revive:
    # golint yerine revive kullanılıyor
    confidence: 0.8

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd              # gomnd yerine mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive           # golint yerine revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    # exportloopref deprecated (Go 1.22+ loopvar ile değiştirildi)
    # maligned deprecated, fieldalignment kullanılıyor (govet içinde)

issues:
  # Yeni format: exclude-dirs ve exclude-files
  exclude-dirs:
    - vendor
    - tmp
  
  exclude-files:
    - ".*_generated\\.go$"
  
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - dupl
        - shadow
        - govet
    
    # Swagger otomatik üretilmiş docs - elle düzenleme önerilmez
    - path: docs/docs\.go
      linters:
        - lll
        - gochecknoinits
    
    # Mock handler test data - magic numbers normal
    - path: internal/api/handlers/mock\.go
      linters:
        - mnd
        - gosec
        - goconst
    
    # Scoring algoritması - magic numbers business logic'in parçası
    - path: internal/domain/scoring/scoring\.go
      linters:
        - mnd
    
    # Test helpers - deprecated testcontainers API (kütüphane güncellemesi gerekir)
    - path: tests/test_helpers\.go
      linters:
        - staticcheck
        - mnd
        - shadow
    
    # Repository interfaces - uzun fonksiyon imzaları kabul edilebilir
    - path: internal/domain/repositories/
      linters:
        - lll
    
    # Repository implementations - uzun SQL query'ler ve Scan satırları
    - path: internal/infrastructure/repository/postgres/
      linters:
        - lll
        - goconst
        - shadow
        - funlen
    
    # Service layer - uzun fonksiyon imzaları kabul edilebilir
    - path: internal/infrastructure/services/
      linters:
        - lll
        - rangeValCopy
        - goconst
        - gocyclo
        - funlen
        - mnd
        - unnamedResult
    
    # Admin routes - complex business logic, magic numbers config değerleri
    - path: internal/api/handlers/admin_routes\.go
      linters:
        - mnd
        - gocyclo
        - goconst
        - funlen
        - lll
    
    # Health handler - timing calculations
    - path: internal/api/handlers/health\.go
      linters:
        - mnd
    
    # Main function - initialization, magic numbers config değerleri
    - path: cmd/api/main\.go
      linters:
        - mnd
        - funlen
        - goconst
        - gocritic
    
    # Database/infrastructure - timeout değerleri
    - path: internal/infrastructure/database/
      linters:
        - mnd
    
    # Middleware - HTTP status codes
    - path: internal/middleware/
      linters:
        - mnd
    
    # Jobs - timing ve configuration
    - path: internal/infrastructure/jobs/
      linters:
        - lll
    
    # Providers - content type string constants (business logic)
    - path: internal/infrastructure/providers/
      linters:
        - goconst
        - rangeValCopy
    
    # API errors - false positive on error code constants
    - path: internal/api/errors\.go
      linters:
        - gosec
    
    - linters:
        - lll
      source: "^//go:generate "
    
    - linters:
        - staticcheck
      text: "SA9003:"
    
    - linters:
        - stylecheck
      text: "ST1000:"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  # skip-dirs ve skip-files kaldırıldı, issues.exclude-dirs/files kullanılıyor
